version: 2.1

executors:
  jdk:
    docker:
      - image: 'cimg/openjdk:11'

orbs:
  maven: circleci/maven@1.4.0
#  tcc: atomicjar/testcontainers-cloud-orb@0.1.0

workflows:
  maven_test:
    jobs:
      - maven/test:
          executor: jdk
#          context: Testcontainers
#          pre-steps:
#            - tcc/setup
